language: cpp
os: windows
jobs:
  include:
  - stage: sysinfo
    script: powershell Get-WmiObject –class Win32_processor | ft systemname,Name,DeviceID,NumberOfCores,NumberOfLogicalProcessors,Addresswidth
